### ISSUE TITLE
font in css of terminal-to-html too ugly

### ISSUE THREAD

**Issue by oldherl** [imlonghao/archlinuxcn-log#7]
You are using the oldest version of assets/terminal.css in the _assets_terminal_css in bindata.go
The font-family is "Monoco, courier" which would fallback to Nimbus Mono L on my system and is very ugly.
Please either change it to just "monospace" and let fontconfig to make the choice, or to follow upstream as it includes "Liberation Mono" now.

**Comment by imlonghao** [comment]
WIP, will update later.

**Comment by imlonghao** [comment]
Fixed @ https://github.com/imlonghao/archlinuxcn-log/commit/40ed38598ca3c81ccd7f979b35d27c1d5beb004d
